import os
import logging
import aiosmtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logger = logging.getLogger(__name__)

DIFFICULTY_COLORS = {
    "Beginner": "#22c55e",
    "Intermediate": "#f59e0b",
    "Advanced": "#ef4444",
}

EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Daily Learning — {title}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ background: #0d1117; color: #e6edf3; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }}
    .wrapper {{ max-width: 640px; margin: 0 auto; padding: 24px 16px; }}
    .header {{ background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 20px 24px; margin-bottom: 16px; }}
    .header h1 {{ font-size: 15px; font-weight: 700; color: #e6edf3; letter-spacing: -0.01em; }}
    .header .date {{ font-size: 12px; color: #8b949e; margin-top: 4px; font-family: monospace; }}
    .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 28px; margin-bottom: 16px; }}
    .topic-title {{ font-size: 22px; font-weight: 700; color: #e6edf3; margin-bottom: 12px; line-height: 1.3; font-family: Georgia, serif; }}
    .badges {{ display: flex; gap: 8px; flex-wrap: wrap; margin-bottom: 20px; }}
    .badge {{ display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; }}
    .badge-domain {{ background: #21262d; color: #8b949e; border: 1px solid #30363d; }}
    .badge-difficulty {{ color: white; }}
    .section {{ margin-bottom: 24px; }}
    .section-title {{ font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #484f58; margin-bottom: 10px; }}
    .section p {{ font-size: 15px; line-height: 1.7; color: #c9d1d9; }}
    .problem-box {{ background: #1a2332; border-left: 3px solid #58a6ff; border-radius: 0 8px 8px 0; padding: 14px 18px; }}
    .problem-box p {{ color: #e6edf3; font-size: 15px; line-height: 1.7; }}
    .takeaways {{ list-style: none; }}
    .takeaways li {{ padding: 8px 0; border-bottom: 1px solid #21262d; font-size: 14px; color: #c9d1d9; }}
    .takeaways li:last-child {{ border-bottom: none; }}
    .takeaways li::before {{ content: "— "; color: #484f58; }}
    .cta {{ background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 20px 28px; text-align: center; }}
    .cta a {{ display: inline-block; background: #238636; color: white; text-decoration: none; padding: 10px 24px; border-radius: 8px; font-weight: 600; font-size: 14px; }}
    .footer {{ text-align: center; padding: 16px; color: #484f58; font-size: 11px; font-family: monospace; }}
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>Daily Learning</h1>
      <div class="date">{date}</div>
    </div>

    <div class="card">
      <div class="topic-title">{title}</div>
      <div class="badges">
        <span class="badge badge-domain">{domain}</span>
        <span class="badge badge-difficulty" style="background: {difficulty_color}20; color: {difficulty_color};">{difficulty}</span>
      </div>

      <div class="section">
        <div class="section-title">The Problem</div>
        <div class="problem-box"><p>{problem_statement}</p></div>
      </div>

      <div class="section">
        <div class="section-title">Context</div>
        <p>{context_snippet}</p>
      </div>

      <div class="section">
        <div class="section-title">Key Takeaways</div>
        <ul class="takeaways">
          {takeaways_html}
        </ul>
      </div>
    </div>

    <div class="cta">
      <p style="color:#8b949e; font-size:13px; margin-bottom:16px;">Read the full breakdown with deep dive, real-world examples and solutions</p>
      <a href="{app_url}">Open Today's Topic →</a>
    </div>

    <div class="footer">
      Daily Learning · Generated by gpt-oss-120b
    </div>
  </div>
</body>
</html>"""


async def send_topic_email(topic: dict, date: str) -> bool:
    smtp_host = os.getenv("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")
    email_to = os.getenv("EMAIL_TO", "")
    app_url = os.getenv("APP_URL", "http://localhost:8080")

    if not all([smtp_user, smtp_password, email_to]):
        logger.warning("Email credentials not configured, skipping email notification")
        return False

    domain = topic.get("domain", "Backend")
    difficulty = topic.get("difficulty", "Intermediate")
    difficulty_color = DIFFICULTY_COLORS.get(difficulty, "#f59e0b")

    takeaways = topic.get("key_takeaways", [])
    takeaways_html = "\n".join(f"<li>{t}</li>" for t in takeaways[:5])

    # Truncate context to first paragraph for email preview
    context = topic.get("context_text", "")
    context_snippet = context.split("\n\n")[0] if "\n\n" in context else context[:300] + "..."

    html_body = EMAIL_TEMPLATE.format(
        title=topic.get("title", "Today's Topic"),
        date=date,
        domain=domain,
        difficulty=difficulty,
        difficulty_color=difficulty_color,
        problem_statement=topic.get("problem_statement", ""),
        context_snippet=context_snippet,
        takeaways_html=takeaways_html,
        app_url=app_url,
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[Important] Daily Learning — {topic.get('title', 'New Topic')}"
    msg["From"] = smtp_user
    msg["To"] = email_to
    msg.attach(MIMEText(html_body, "html"))

    try:
        await aiosmtplib.send(
            msg,
            hostname=smtp_host,
            port=smtp_port,
            start_tls=True,
            username=smtp_user,
            password=smtp_password,
        )
        logger.info(f"Email sent to {email_to}")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False
